# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  # facebook_sync:
  #   class: FacebookSyncJob
  #   schedule: every 240 minutes
  # hourly_stat:
  #   class: HourlyStatJob
  #   schedule: every hour
  bigquery_sync:
    class: BigquerySyncJob
    schedule: every 10 minutes
  data_cleanup:
    class: DataCleanupJob
    schedule: every day at 2am
  hubspot_sync:
    class: HubspotSyncJob
    schedule: every 60 minutes
