# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
production:
  facebook_sync:
    class: FacebookSyncJob
    schedule: every 30 minutes
  facebook_audience_sync:
    class: FacebookAudienceSyncJob
    schedule: every 60 minutes
  hourly_stat:
    class: HourlyStatJob
    schedule: every hour
  bigquery_sync:
    class: BigquerySyncJob
    schedule: every 60 minutes
  data_cleanup:
    class: DataCleanupJob
    schedule: every day at 2am
  hubspot_sync:
    class: HubspotSyncJob
    schedule: every 30 minutes
  hubspot_bigquery_sync:
    class: HubspotBigquerySyncJob
    schedule: every 6 hours
  # Individual object syncs to distribute load
  # hubspot_core_sync:
  #   class: HubspotBigquerySyncJob
  #   args: ["contacts"]
  #   schedule: every 6 hours
  # hubspot_deals_sync:
  #   class: HubspotBigquerySyncJob
  #   args: ["deals"]
  #   schedule: every 6 hours
  # hubspot_activities_sync:
  #   class: HubspotBigquerySyncJob
  #   args: ["engagements"]
  #   schedule: every 8 hours